changelog:
  categories:
    - title: "✨ New Features"
      labels:
        - feature
        - performance
    - title: "🐛 Bug Fixes"
      labels:
        - fix
        - bug
    - title: "🔧 Maintenance"
      labels:
        - chore
        - refactor
        - style
        - test
        - build
        - CI/CD
    - title: "📝 Documentation"
      labels:
        - documentation
    - title: "📦 Other Changes"
      labels:
        - "*"
